### ISSUE TITLE
Add sqoop tool to pipeline

### ISSUE THREAD

**Issue by p12masaf** [apssouza22/lambda-arch#11]
Hi,

I want to add Sqoop tool to import data from RDBMS to HDFS. How can I configure the ecosystem that you has created to include this tool? The tool may be installed on namenode image?

Congratulation for the project, it is a great work. Thank you.

**Comment by apssouza22** [comment]
Hi, the same way I am saving from Spark you will do with Sqoop. That means, create a new docker container for Sqoop and access the HDFS from there.

**Comment by p12masaf** [comment]
Hi, I will try the solution you have mentioned. Thank you.
