### ISSUE TITLE
Docker Compose Up Fails

### ISSUE THREAD

**Issue by yunus89** [apssouza22/lambda-arch#2]
C:\Users\Yunus\Documents\dataengineer\lambda-arch>docker-compose -p lambda up
    Creating zookeeper-iot ...
    Creating cassandra-iot ... error
    Creating zookeeper-iot  ... done
    Creating namenode      ...
    Creating spark-master  ... done
    Creating namenode       ... done
    Creating spark-worker-1 ... done
    Creating kafka-iot      ... done
    Creating datanode       ... done

    ERROR: for cassandra  user specified IP address is supported only when connecting to networks with user configured subnets
    ERROR: Encountered errors while bringing up the project.

When `docker-compose -p lambda up` i get error above. How can i fix it?

    $ docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server: Docker Engine - Community
 Engine:
  Version:      18.09.1
  API version:  1.39 (minimum version 1.12)
  Go version:   go1.10.6
  Git commit:   4c52b90
  Built:        Wed Jan  9 19:41:57 2019
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by apssouza22** [comment]
I think I saw it happen before and after running it again it worked. Did you try to run it again?

**Comment by apssouza22** [comment]
@yunus89 ?

**Comment by yunus89** [comment]
Sorry for the late reply, i shutdown the services and ran them again the error just didnt happen.

Thanks, and by the way, nice lambda architecture example for data engineering enthusiast like me
